import '../reservas_restaurantes_nine_screen/widgets/userslider_item_widget.dart';import '../reservas_restaurantes_nine_screen/widgets/widgetchipview_item_widget.dart';import 'bloc/reservas_restaurantes_nine_bloc.dart';import 'models/reservas_restaurantes_nine_model.dart';import 'models/userslider_item_model.dart';import 'models/widgetchipview_item_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_forty_page/inicio_de_sesi_n_forty_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_fortynine_page/inicio_de_sesi_n_fortynine_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_ninetytwo_page/inicio_de_sesi_n_ninetytwo_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_twentyone_page/inicio_de_sesi_n_twentyone_page.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:asaf_s_application2/widgets/custom_bottom_bar.dart';import 'package:asaf_s_application2/widgets/custom_drop_down.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ReservasRestaurantesNineScreen extends StatelessWidget {ReservasRestaurantesNineScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<ReservasRestaurantesNineBloc>(create: (context) => ReservasRestaurantesNineBloc(ReservasRestaurantesNineState(reservasRestaurantesNineModelObj: ReservasRestaurantesNineModel()))..add(ReservasRestaurantesNineInitialEvent()), child: ReservasRestaurantesNineScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildUserSlider(context), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_informaci_n".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 9.v), Container(width: 359.h, margin: EdgeInsets.only(left: 16.h, right: 36.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallOnPrimary)), SizedBox(height: 6.v), _buildAsientosColumn(context), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_servicios".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 9.v), _buildWidgetChipView(context)])), Spacer()])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildBottomBar(context)))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_mesa_vip_1".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildUserSlider(BuildContext context) { return BlocBuilder<ReservasRestaurantesNineBloc, ReservasRestaurantesNineState>(builder: (context, state) {return CarouselSlider.builder(options: CarouselOptions(height: 252.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {state.sliderIndex = index;}), itemCount: state.reservasRestaurantesNineModelObj?.usersliderItemList.length ?? 0, itemBuilder: (context, index, realIndex) {UsersliderItemModel model = state.reservasRestaurantesNineModelObj?.usersliderItemList[index] ?? UsersliderItemModel(); return UsersliderItemWidget(model);});}); } 
/// Section Widget
Widget _buildAsientosColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_asientos".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 11.v), BlocSelector<ReservasRestaurantesNineBloc, ReservasRestaurantesNineState, ReservasRestaurantesNineModel?>(selector: (state) => state.reservasRestaurantesNineModelObj, builder: (context, reservasRestaurantesNineModelObj) {return CustomDropDown(width: 120.h, icon: Container(margin: EdgeInsets.only(left: 30.h), child: CustomImageView(imagePath: ImageConstant.imgFlechaSeleccionarOnprimary, height: 28.adaptSize, width: 28.adaptSize)), hintText: "lbl_4_8".tr, items: reservasRestaurantesNineModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 8.h, top: 17.v, bottom: 17.v), borderDecoration: DropDownStyleHelper.outlineGrayTL8, onChanged: (value) {context.read<ReservasRestaurantesNineBloc>().add(ChangeDropDownEvent(value: value));});})])); } 
/// Section Widget
Widget _buildWidgetChipView(BuildContext context) { return Align(alignment: Alignment.center, child: BlocSelector<ReservasRestaurantesNineBloc, ReservasRestaurantesNineState, ReservasRestaurantesNineModel?>(selector: (state) => state.reservasRestaurantesNineModelObj, builder: (context, reservasRestaurantesNineModelObj) {return Wrap(runSpacing: 16.v, spacing: 16.h, children: List<Widget>.generate(reservasRestaurantesNineModelObj?.widgetchipviewItemList.length ?? 0, (index) {WidgetchipviewItemModel model = reservasRestaurantesNineModelObj?.widgetchipviewItemList[index] ?? WidgetchipviewItemModel(); return WidgetchipviewItemWidget(model, onSelectedChipView: (value) {context.read<ReservasRestaurantesNineBloc>().add(UpdateChipViewEvent(index: index, isSelected: value));});}));})); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Promociones: return AppRoutes.inicioDeSesiNTwentyonePage; case BottomBarEnum.Favoritos: return AppRoutes.inicioDeSesiNFortyPage; case BottomBarEnum.Cercadem: return AppRoutes.inicioDeSesiNFortyninePage; case BottomBarEnum.Pickup: return AppRoutes.inicioDeSesiNNinetytwoPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.inicioDeSesiNTwentyonePage: return InicioDeSesiNTwentyonePage(); case AppRoutes.inicioDeSesiNFortyPage: return InicioDeSesiNFortyPage(); case AppRoutes.inicioDeSesiNFortyninePage: return InicioDeSesiNFortyninePage(); case AppRoutes.inicioDeSesiNNinetytwoPage: return InicioDeSesiNNinetytwoPage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
