import 'bloc/inicio_de_sesi_n_fortythree_bloc.dart';import 'models/inicio_de_sesi_n_fortythree_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_forty_page/inicio_de_sesi_n_forty_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_fortynine_page/inicio_de_sesi_n_fortynine_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_ninetytwo_page/inicio_de_sesi_n_ninetytwo_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_twentyone_page/inicio_de_sesi_n_twentyone_page.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:asaf_s_application2/widgets/custom_bottom_bar.dart';import 'package:asaf_s_application2/widgets/custom_elevated_button.dart';import 'package:asaf_s_application2/widgets/custom_floating_text_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InicioDeSesiNFortythreeScreen extends StatelessWidget {InicioDeSesiNFortythreeScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNFortythreeBloc>(create: (context) => InicioDeSesiNFortythreeBloc(InicioDeSesiNFortythreeState(inicioDeSesiNFortythreeModelObj: InicioDeSesiNFortythreeModel()))..add(InicioDeSesiNFortythreeInitialEvent()), child: InicioDeSesiNFortythreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 6.v), Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, children: [Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_datos_de_la_reserva".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 17.v), _buildUploadTextField1(context), SizedBox(height: 14.v), _buildUploadTextField2(context), SizedBox(height: 14.v), _buildUploadTextField3(context), SizedBox(height: 14.v), _buildUploadTextField4(context), SizedBox(height: 14.v), _buildUploadTextField5(context), SizedBox(height: 14.v), _buildUploadTextField6(context), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapTxtActions(context);}, child: Text(""))]), SizedBox(height: 15.v), _buildVerQrButton(context)]))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildBottomBar(context))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v)), centerTitle: true, title: AppbarTitle(text: "lbl_product".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildUploadTextField1(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField1Controller, builder: (context, uploadTextField1Controller) {return CustomFloatingTextField(controller: uploadTextField1Controller, labelText: "msg_usuario_que_realiz".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "msg_usuario_que_realiz".tr, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 64.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v), borderDecoration: FloatingTextFormFieldStyleHelper.fillPrimaryContainer, filled: true, fillColor: theme.colorScheme.primaryContainer);}); } 
/// Section Widget
Widget _buildUploadTextField2(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField2Controller, builder: (context, uploadTextField2Controller) {return CustomFloatingTextField(controller: uploadTextField2Controller, labelText: "lbl_invitado_1".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "lbl_invitado_1".tr, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 65.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v));}); } 
/// Section Widget
Widget _buildUploadTextField3(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField3Controller, builder: (context, uploadTextField3Controller) {return CustomFloatingTextField(controller: uploadTextField3Controller, labelText: "lbl_invitado_2".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "lbl_invitado_2".tr, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 65.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v), borderDecoration: FloatingTextFormFieldStyleHelper.fillPrimaryContainer, filled: true, fillColor: theme.colorScheme.primaryContainer);}); } 
/// Section Widget
Widget _buildUploadTextField4(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField4Controller, builder: (context, uploadTextField4Controller) {return CustomFloatingTextField(controller: uploadTextField4Controller, labelText: "lbl_invitado_3".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "lbl_invitado_3".tr, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 65.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v));}); } 
/// Section Widget
Widget _buildUploadTextField5(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField5Controller, builder: (context, uploadTextField5Controller) {return CustomFloatingTextField(controller: uploadTextField5Controller, labelText: "lbl_invitado_4".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "lbl_invitado_4".tr, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 65.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v));}); } 
/// Section Widget
Widget _buildUploadTextField6(BuildContext context) { return BlocSelector<InicioDeSesiNFortythreeBloc, InicioDeSesiNFortythreeState, TextEditingController?>(selector: (state) => state.uploadTextField6Controller, builder: (context, uploadTextField6Controller) {return CustomFloatingTextField(controller: uploadTextField6Controller, labelText: "lbl_invitado_5".tr, labelStyle: CustomTextStyles.bodyLargeGray9000116, hintText: "lbl_invitado_5".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 65.v), contentPadding: EdgeInsets.fromLTRB(16.h, 15.v, 16.h, 16.v), borderDecoration: FloatingTextFormFieldStyleHelper.fillPrimaryContainer, filled: true, fillColor: theme.colorScheme.primaryContainer);}); } 
/// Section Widget
Widget _buildVerQrButton(BuildContext context) { return CustomElevatedButton(width: 121.h, text: "lbl_ver_qr".tr, leftIcon: Container(margin: EdgeInsets.only(right: 12.h), child: CustomImageView(imagePath: ImageConstant.imgPrinter, height: 24.adaptSize, width: 24.adaptSize)), onPressed: () {onTapVerQrButton(context);}, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Promociones: return AppRoutes.inicioDeSesiNTwentyonePage; case BottomBarEnum.Favoritos: return AppRoutes.inicioDeSesiNFortyPage; case BottomBarEnum.Cercadem: return AppRoutes.inicioDeSesiNFortyninePage; case BottomBarEnum.Pickup: return AppRoutes.inicioDeSesiNNinetytwoPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.inicioDeSesiNTwentyonePage: return InicioDeSesiNTwentyonePage(); case AppRoutes.inicioDeSesiNFortyPage: return InicioDeSesiNFortyPage(); case AppRoutes.inicioDeSesiNFortyninePage: return InicioDeSesiNFortyninePage(); case AppRoutes.inicioDeSesiNNinetytwoPage: return InicioDeSesiNNinetytwoPage(); default: return DefaultWidget();} } 
/// Navigates to the inicioDeSesiNFortytwoScreen when the action is triggered.
onTapTxtActions(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNFortytwoScreen, ); } 
/// Navigates to the inicioDeSesiNFortyfourScreen when the action is triggered.
onTapVerQrButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNFortyfourScreen, ); } 
 }
