import '../inicio_de_sesi_n_forty_page/widgets/reservaactivalist1_item_widget.dart';import '../inicio_de_sesi_n_forty_page/widgets/reservaactivalist_item_widget.dart';import 'bloc/inicio_de_sesi_n_forty_bloc.dart';import 'models/inicio_de_sesi_n_forty_model.dart';import 'models/reservaactivalist1_item_model.dart';import 'models/reservaactivalist_item_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class InicioDeSesiNFortyPage extends StatelessWidget {const InicioDeSesiNFortyPage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNFortyBloc>(create: (context) => InicioDeSesiNFortyBloc(InicioDeSesiNFortyState(inicioDeSesiNFortyModelObj: InicioDeSesiNFortyModel()))..add(InicioDeSesiNFortyInitialEvent()), child: InicioDeSesiNFortyPage()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 724.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 8.h), child: Stack(alignment: Alignment.center, children: [SizedBox(width: double.maxFinite, child: Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_reservas_activas".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 17.v), _buildReservaActivaList(context), SizedBox(height: 15.v), Text("lbl_mis_favoritos".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 17.v), _buildReservaActivaList1(context)])))), Align(alignment: Alignment.center, child: Container(height: 852.v, width: 412.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(18.h), border: Border.all(color: appTheme.gray6007f, width: 8.h, strokeAlign: strokeAlignOutside))))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v)), centerTitle: true, title: AppbarTitle(text: "lbl_product".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildReservaActivaList(BuildContext context) { return Expanded(child: BlocSelector<InicioDeSesiNFortyBloc, InicioDeSesiNFortyState, InicioDeSesiNFortyModel?>(selector: (state) => state.inicioDeSesiNFortyModelObj, builder: (context, inicioDeSesiNFortyModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: inicioDeSesiNFortyModelObj?.reservaactivalistItemList.length ?? 0, itemBuilder: (context, index) {ReservaactivalistItemModel model = inicioDeSesiNFortyModelObj?.reservaactivalistItemList[index] ?? ReservaactivalistItemModel(); return ReservaactivalistItemWidget(model, onTapReservaActiva: () {onTapReservaActiva(context);});});})); } 
/// Section Widget
Widget _buildReservaActivaList1(BuildContext context) { return BlocSelector<InicioDeSesiNFortyBloc, InicioDeSesiNFortyState, InicioDeSesiNFortyModel?>(selector: (state) => state.inicioDeSesiNFortyModelObj, builder: (context, inicioDeSesiNFortyModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: inicioDeSesiNFortyModelObj?.reservaactivalist1ItemList.length ?? 0, itemBuilder: (context, index) {Reservaactivalist1ItemModel model = inicioDeSesiNFortyModelObj?.reservaactivalist1ItemList[index] ?? Reservaactivalist1ItemModel(); return Reservaactivalist1ItemWidget(model);});}); } 
/// Navigates to the inicioDeSesiNFortyoneScreen when the action is triggered.
onTapReservaActiva(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNFortyoneScreen, ); } 
 }
