import 'bloc/inicio_de_sesi_n_sixtyeight_bloc.dart';import 'models/inicio_de_sesi_n_sixtyeight_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_forty_page/inicio_de_sesi_n_forty_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_fortynine_page/inicio_de_sesi_n_fortynine_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_ninetytwo_page/inicio_de_sesi_n_ninetytwo_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_twentyone_page/inicio_de_sesi_n_twentyone_page.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:asaf_s_application2/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InicioDeSesiNSixtyeightScreen extends StatelessWidget {InicioDeSesiNSixtyeightScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNSixtyeightBloc>(create: (context) => InicioDeSesiNSixtyeightBloc(InicioDeSesiNSixtyeightState(inicioDeSesiNSixtyeightModelObj: InicioDeSesiNSixtyeightModel()))..add(InicioDeSesiNSixtyeightInitialEvent()), child: InicioDeSesiNSixtyeightScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<InicioDeSesiNSixtyeightBloc, InicioDeSesiNSixtyeightState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Container(height: 1043.v, width: 412.h, margin: EdgeInsets.symmetric(horizontal: 8.h), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildWelcomeMessageRow(context), SizedBox(height: 16.v), Column(children: [CustomImageView(imagePath: ImageConstant.imgMedia, height: 188.v, width: 380.h, radius: BorderRadius.vertical(top: Radius.circular(18.h))), _buildPaymentMethodsColumn(context), SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgRectangle12427, height: 180.v, width: 380.h, radius: BorderRadius.vertical(top: Radius.circular(18.h))), Container(width: 380.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 10.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL181), child: Text("lbl_cupones".tr, style: CustomTextStyles.titleLargeOnPrimary))]), SizedBox(height: 16.v), _buildDiamondRow(context), SizedBox(height: 16.v), _buildHelpRow(context), _buildReviewsRow(context, gradeImage: ImageConstant.imgMapsUgc, listaTitulo: "lbl_comentarios".tr), _buildReviewsRow(context, gradeImage: ImageConstant.imgGrade, listaTitulo: "lbl_valoraciones".tr), _buildReviewsRow(context, gradeImage: ImageConstant.imgCreditCard, listaTitulo: "msg_historial_de_pagos".tr)]))), Align(alignment: Alignment.topCenter, child: Container(height: 852.v, width: 412.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(18.h), border: Border.all(color: appTheme.gray6007f, width: 8.h, strokeAlign: strokeAlignOutside))))])))), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildBottomBar(context))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v)), centerTitle: true, title: AppbarTitle(text: "lbl_men".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildWelcomeMessageRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 1.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgClose18x18, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v), onTap: () {onTapImgClose(context);}), Container(width: 202.h, margin: EdgeInsets.only(left: 22.h, top: 8.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_le_damos_la_bienvenida".tr, style: theme.textTheme.titleMedium), TextSpan(text: "msg_mar_a_fernanda_flores".tr, style: theme.textTheme.bodySmall)]), textAlign: TextAlign.left))])); } 
/// Section Widget
Widget _buildPaymentMethodsColumn(BuildContext context) { return Container(width: 380.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL181), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_cartera".tr, style: CustomTextStyles.titleLargeOnPrimary), Text("lbl_m_todos_de_pago".tr, style: CustomTextStyles.bodyMedium_1)])); } 
/// Section Widget
Widget _buildDiamondRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 6.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDiamond, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 9.v)), Container(width: 187.h, margin: EdgeInsets.only(left: 22.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_nete_a_nosotros".tr, style: theme.textTheme.titleMedium), TextSpan(text: "msg_registra_tu_negocio".tr, style: theme.textTheme.bodySmall)]), textAlign: TextAlign.left))])), CustomImageView(imagePath: ImageConstant.imgFlechaSeleccionarOnprimarycontainer, height: 48.adaptSize, width: 48.adaptSize, margin: EdgeInsets.symmetric(vertical: 7.v))])); } 
/// Section Widget
Widget _buildHelpRow(BuildContext context) { return Container(padding: EdgeInsets.fromLTRB(16.h, 8.v, 16.h, 7.v), decoration: AppDecoration.outlineGray600, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLiveHelp, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v)), Padding(padding: EdgeInsets.only(left: 22.h, top: 14.v, bottom: 9.v), child: Text("lbl_ayuda".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(imagePath: ImageConstant.imgFlechaSeleccionarOnprimarycontainer, height: 48.adaptSize, width: 48.adaptSize)])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Common widget
Widget _buildReviewsRow(BuildContext context, {required String gradeImage, required String listaTitulo, }) { return Container(padding: EdgeInsets.only(top: 8.v, bottom: 7.v), decoration: AppDecoration.outlineGray600, child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [CustomImageView(imagePath: gradeImage, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v)), Padding(padding: EdgeInsets.symmetric(vertical: 12.v), child: Text(listaTitulo, style: theme.textTheme.titleMedium!.copyWith(color: theme.colorScheme.onPrimaryContainer))), CustomImageView(imagePath: ImageConstant.imgFlechaSeleccionarOnprimarycontainer, height: 48.adaptSize, width: 48.adaptSize)])); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Promociones: return AppRoutes.inicioDeSesiNTwentyonePage; case BottomBarEnum.Favoritos: return AppRoutes.inicioDeSesiNFortyPage; case BottomBarEnum.Cercadem: return AppRoutes.inicioDeSesiNFortyninePage; case BottomBarEnum.Pickup: return AppRoutes.inicioDeSesiNNinetytwoPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.inicioDeSesiNTwentyonePage: return InicioDeSesiNTwentyonePage(); case AppRoutes.inicioDeSesiNFortyPage: return InicioDeSesiNFortyPage(); case AppRoutes.inicioDeSesiNFortyninePage: return InicioDeSesiNFortyninePage(); case AppRoutes.inicioDeSesiNNinetytwoPage: return InicioDeSesiNNinetytwoPage(); default: return DefaultWidget();} } 

/// Navigates to the previous screen.
onTapImgClose(BuildContext context) { NavigatorService.goBack(); } 
 }
