import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_sixteen_screen/models/inicio_de_sesi_n_sixteen_model.dart';part 'inicio_de_sesi_n_sixteen_event.dart';part 'inicio_de_sesi_n_sixteen_state.dart';/// A bloc that manages the state of a InicioDeSesiNSixteen according to the event that is dispatched to it.
class InicioDeSesiNSixteenBloc extends Bloc<InicioDeSesiNSixteenEvent, InicioDeSesiNSixteenState> {InicioDeSesiNSixteenBloc(InicioDeSesiNSixteenState initialState) : super(initialState) { on<InicioDeSesiNSixteenInitialEvent>(_onInitialize); on<ChangeDropDownEvent>(_changeDropDown); on<ChangeDropDown1Event>(_changeDropDown1); on<ChangeDropDown2Event>(_changeDropDown2); }

_changeDropDown(ChangeDropDownEvent event, Emitter<InicioDeSesiNSixteenState> emit, ) { emit(state.copyWith(selectedDropDownValue: event.value)); } 
_changeDropDown1(ChangeDropDown1Event event, Emitter<InicioDeSesiNSixteenState> emit, ) { emit(state.copyWith(selectedDropDownValue1: event.value)); } 
_changeDropDown2(ChangeDropDown2Event event, Emitter<InicioDeSesiNSixteenState> emit, ) { emit(state.copyWith(selectedDropDownValue2: event.value)); } 
List<SelectionPopupModel> fillDropdownItemList() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList1() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList2() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
_onInitialize(InicioDeSesiNSixteenInitialEvent event, Emitter<InicioDeSesiNSixteenState> emit, ) async  { emit(state.copyWith(firstNameController: TextEditingController(), lastNameController: TextEditingController(), usernameController: TextEditingController())); emit(state.copyWith(inicioDeSesiNSixteenModelObj: state.inicioDeSesiNSixteenModelObj?.copyWith(dropdownItemList: fillDropdownItemList(), dropdownItemList1: fillDropdownItemList1(), dropdownItemList2: fillDropdownItemList2()))); } 
 }
