import 'bloc/inicio_de_sesi_n_fortyseven_bloc.dart';import 'models/inicio_de_sesi_n_fortyseven_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_forty_page/inicio_de_sesi_n_forty_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_fortynine_page/inicio_de_sesi_n_fortynine_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_ninetytwo_page/inicio_de_sesi_n_ninetytwo_page.dart';import 'package:asaf_s_application2/presentation/inicio_de_sesi_n_twentyone_page/inicio_de_sesi_n_twentyone_page.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:asaf_s_application2/widgets/custom_bottom_bar.dart';import 'package:asaf_s_application2/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InicioDeSesiNFortysevenScreen extends StatelessWidget {InicioDeSesiNFortysevenScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNFortysevenBloc>(create: (context) => InicioDeSesiNFortysevenBloc(InicioDeSesiNFortysevenState(inicioDeSesiNFortysevenModelObj: InicioDeSesiNFortysevenModel()))..add(InicioDeSesiNFortysevenInitialEvent()), child: InicioDeSesiNFortysevenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 8.v), Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, children: [BlocSelector<InicioDeSesiNFortysevenBloc, InicioDeSesiNFortysevenState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_karaoke_fortuna2".tr);}), SizedBox(height: 24.v), SizedBox(height: 600.v, width: 380.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgIntersect300x264, height: 600.v, width: 380.h, radius: BorderRadius.circular(28.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgLocationOn, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 199.v, right: 70.h), onTap: () {onTapImgLocationOn(context);})]))]))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildBottomBar(context)))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v)), centerTitle: true, title: AppbarTitle(text: "lbl_cerca_de_m".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Promociones: return AppRoutes.inicioDeSesiNTwentyonePage; case BottomBarEnum.Favoritos: return AppRoutes.inicioDeSesiNFortyPage; case BottomBarEnum.Cercadem: return AppRoutes.inicioDeSesiNFortyninePage; case BottomBarEnum.Pickup: return AppRoutes.inicioDeSesiNNinetytwoPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.inicioDeSesiNTwentyonePage: return InicioDeSesiNTwentyonePage(); case AppRoutes.inicioDeSesiNFortyPage: return InicioDeSesiNFortyPage(); case AppRoutes.inicioDeSesiNFortyninePage: return InicioDeSesiNFortyninePage(); case AppRoutes.inicioDeSesiNNinetytwoPage: return InicioDeSesiNNinetytwoPage(); default: return DefaultWidget();} } 
/// Navigates to the inicioDeSesiNFortyeightScreen when the action is triggered.
onTapImgLocationOn(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNFortyeightScreen, ); } 
 }
