import 'bloc/inicio_de_sesi_n_one_bloc.dart';import 'models/inicio_de_sesi_n_one_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/core/utils/validation_functions.dart';import 'package:asaf_s_application2/widgets/custom_outlined_button.dart';import 'package:asaf_s_application2/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InicioDeSesiNOneScreen extends StatelessWidget {InicioDeSesiNOneScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNOneBloc>(create: (context) => InicioDeSesiNOneBloc(InicioDeSesiNOneState(inicioDeSesiNOneModelObj: InicioDeSesiNOneModel()))..add(InicioDeSesiNOneInitialEvent()), child: InicioDeSesiNOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer, resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 8.h), child: Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.gray6007f, width: 8.h), borderRadius: BorderRadiusStyle.roundedBorder18), child: Container(height: 852.v, width: 412.h, decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgIntersect, height: 852.v, width: 412.h, radius: BorderRadius.circular(18.h), alignment: Alignment.center), _buildModalInicioDe(context)]))))))); } 
/// Section Widget
Widget _buildModalInicioDe(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 50.h, top: 238.v, right: 50.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL28), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_iniciar_sesi_n".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 15.v), BlocSelector<InicioDeSesiNOneBloc, InicioDeSesiNOneState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "msg_iniciar_sesi_n_con".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 11.v, 8.h, 11.v), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 18.adaptSize, width: 18.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.only(top: 11.v, right: 30.h, bottom: 11.v));}), SizedBox(height: 16.v), CustomOutlinedButton(text: "msg_iniciar_sesi_n_con2".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 18.adaptSize, width: 18.adaptSize))), SizedBox(height: 16.v), CustomOutlinedButton(text: "msg_iniciar_sesi_n_con3".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgIconPrimarycontainer, height: 18.adaptSize, width: 18.adaptSize))), SizedBox(height: 16.v), CustomOutlinedButton(text: "msg_iniciar_sesi_n_con4".tr, leftIcon: Container(margin: EdgeInsets.only(right: 9.h), child: CustomImageView(imagePath: ImageConstant.imgPlay, height: 15.adaptSize, width: 15.adaptSize)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 15.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL28), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [GestureDetector(onTap: () {onTapTxtRegistro(context);}, child: Padding(padding: EdgeInsets.only(left: 5.h, bottom: 6.v), child: Text("lbl_registro".tr, style: CustomTextStyles.labelLargePrimary))), GestureDetector(onTap: () {onTapTxtOlvidastelacontrasea(context);}, child: Padding(padding: EdgeInsets.only(bottom: 6.v), child: Text("msg_olvidaste_la_contrase_a".tr, style: CustomTextStyles.labelLargeRed900)))]))]))); } 
/// Navigates to the inicioDeSesiNFourteenScreen when the action is triggered.
onTapTxtRegistro(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNFourteenScreen, ); } 
/// Navigates to the inicioDeSesiNSevenScreen when the action is triggered.
onTapTxtOlvidastelacontrasea(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inicioDeSesiNSevenScreen, ); } 
 }
