import '../inicio_de_sesi_n_sixtythree_screen/widgets/listamodal_item_widget.dart';import 'bloc/inicio_de_sesi_n_sixtythree_bloc.dart';import 'models/inicio_de_sesi_n_sixtythree_model.dart';import 'models/listamodal_item_model.dart';import 'package:asaf_s_application2/core/app_export.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_title.dart';import 'package:asaf_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:asaf_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:asaf_s_application2/widgets/custom_drop_down.dart';import 'package:flutter/material.dart';class InicioDeSesiNSixtythreeScreen extends StatelessWidget {const InicioDeSesiNSixtythreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<InicioDeSesiNSixtythreeBloc>(create: (context) => InicioDeSesiNSixtythreeBloc(InicioDeSesiNSixtythreeState(inicioDeSesiNSixtythreeModelObj: InicioDeSesiNSixtythreeModel()))..add(InicioDeSesiNSixtythreeInitialEvent()), child: InicioDeSesiNSixtythreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 8.h), child: Container(width: 412.h, decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 14.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_selecci_n_de_reas".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 18.v), BlocSelector<InicioDeSesiNSixtythreeBloc, InicioDeSesiNSixtythreeState, InicioDeSesiNSixtythreeModel?>(selector: (state) => state.inicioDeSesiNSixtythreeModelObj, builder: (context, inicioDeSesiNSixtythreeModelObj) {return CustomDropDown(width: 120.h, icon: Container(margin: EdgeInsets.only(left: 30.h), child: CustomImageView(imagePath: ImageConstant.imgFlechaSeleccionarOnprimary, height: 28.adaptSize, width: 28.adaptSize)), hintText: "lbl_6".tr, items: inicioDeSesiNSixtythreeModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<InicioDeSesiNSixtythreeBloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 16.v), _buildListaModal(context)])), Spacer(), _buildComponentNinetyNine(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v)), centerTitle: true, title: AppbarTitle(text: "lbl_product".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildListaModal(BuildContext context) { return BlocSelector<InicioDeSesiNSixtythreeBloc, InicioDeSesiNSixtythreeState, InicioDeSesiNSixtythreeModel?>(selector: (state) => state.inicioDeSesiNSixtythreeModelObj, builder: (context, inicioDeSesiNSixtythreeModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: inicioDeSesiNSixtythreeModelObj?.listamodalItemList.length ?? 0, itemBuilder: (context, index) {ListamodalItemModel model = inicioDeSesiNSixtythreeModelObj?.listamodalItemList[index] ?? ListamodalItemModel(); return ListamodalItemWidget(model, onTapListaModal: () {onTapListaModal(context);});});}); } 
/// Section Widget
Widget _buildComponentNinetyNine(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 14.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL181), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_total".tr, style: theme.textTheme.bodyLarge)), Spacer(), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("lbl".tr, style: theme.textTheme.bodyLarge)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_0".tr, style: theme.textTheme.bodyLarge)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_00".tr, style: theme.textTheme.bodyLarge)), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("lbl_mxn".tr, style: theme.textTheme.bodyLarge))])); } 
/// Navigates to the reservasRestaurantesTenScreen when the action is triggered.
onTapListaModal(BuildContext context) { NavigatorService.pushNamed(AppRoutes.reservasRestaurantesTenScreen, ); } 
 }
